//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorLabServicios.ServiceReferenceSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSOAP.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConexionDBResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConexionDB", ReplyAction="*")]
        ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse ConexionDB(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConexionDB", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse> ConexionDBAsync(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse obtenerCotizacion(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse> obtenerCotizacionAsync(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse registrarCotizacion(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse> registrarCotizacionAsync(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConexionDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConexionDB", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequestBody Body;
        
        public ConexionDBRequest() {
        }
        
        public ConexionDBRequest(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConexionDBRequestBody {
        
        public ConexionDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConexionDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConexionDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponseBody Body;
        
        public ConexionDBResponse() {
        }
        
        public ConexionDBResponse(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConexionDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConexionDBResult;
        
        public ConexionDBResponseBody() {
        }
        
        public ConexionDBResponseBody(string ConexionDBResult) {
            this.ConexionDBResult = ConexionDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(string obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest() {
        }
        
        public registrarCotizacionRequest(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double monto_oficial;
        
        public registrarCotizacionRequestBody() {
        }
        
        public registrarCotizacionRequestBody(string fecha, double monto, double monto_oficial) {
            this.fecha = fecha;
            this.monto = monto;
            this.monto_oficial = monto_oficial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse() {
        }
        
        public registrarCotizacionResponse(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody() {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult) {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap>, ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.ConexionDB(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest request) {
            return base.Channel.ConexionDB(request);
        }
        
        public string ConexionDB() {
            ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequestBody();
            ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse retVal = ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).ConexionDB(inValue);
            return retVal.Body.ConexionDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse> ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.ConexionDBAsync(ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest request) {
            return base.Channel.ConexionDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBResponse> ConexionDBAsync() {
            ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.ConexionDBRequestBody();
            return ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).ConexionDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.obtenerCotizacion(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public string obtenerCotizacion(string fecha) {
            ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse retVal = ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse> ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.obtenerCotizacionAsync(ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionResponse> obtenerCotizacionAsync(string fecha) {
            ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.registrarCotizacion(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(string fecha, double monto, double monto_oficial) {
            ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            inValue.Body.monto_oficial = monto_oficial;
            ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse retVal = ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse> ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap.registrarCotizacionAsync(ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionResponse> registrarCotizacionAsync(string fecha, double monto, double monto_oficial) {
            ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest inValue = new ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequest();
            inValue.Body = new ConsumidorLabServicios.ServiceReferenceSOAP.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            inValue.Body.monto_oficial = monto_oficial;
            return ((ConsumidorLabServicios.ServiceReferenceSOAP.WebServiceSoap)(this)).registrarCotizacionAsync(inValue);
        }
    }
}
